<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Vieworder.aspx.cs" Inherits="andrewscanteensystem.Vieworder" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link href="Content/bootstrap.min.css" rel="stylesheet" />
    <script src="Scripts/jquery-3.0.0.min.js"></script>
    <script src="Scripts/bootstrap.min.js"></script>
    	<link rel="stylesheet" type="text/css" href="Style1.css" />

    <title></title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">St. Andrew's Canteen</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="menu.aspx">Orders<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="stock.aspx">Stock</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="Report.aspx">Reports</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="employee.aspx">Employee</a>
      </li>
        </ul>
                 <asp:Label ID="Label2" runat="server" Text="Label" ></asp:Label>


    <form class="form-inline my-2 my-lg-0">
        <ul class="navbar-nav mr-auto">
       <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="Coupon.aspx">Coupons</a>
          
          <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="coupons.aspx" id="swer">Logout</a>

          </div>
         
      </li>
            
        
        </ul>
    </form>
  </div>
</nav>
    <form id="form1" runat="server">
        <div>
            <div style="margin-left: auto; margin-right: auto; text-align: center;">
                 <h2><asp:Label ID="Label5" runat="server" Text="Orders"></asp:Label></h2>

         
         </div>
            <br />
            <br />
           <h6> &nbsp;&nbsp;&nbsp;&nbsp;Select A Particular Order ID:&nbsp;&nbsp;
            <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource1" DataTextField="orderid" DataValueField="orderid">
            </asp:DropDownList>
            &nbsp;&nbsp;
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="View Order Details" class="btn btn-dark" /> &nbsp;&nbsp;&nbsp;<asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Hide Order Details" class="btn btn-dark" />&nbsp;&nbsp;&nbsp;&nbsp;
               </h6>
            
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="View All Orders" class="btn btn-dark" Height="38px" Width="160px" />&nbsp;&nbsp;&nbsp;
            <asp:Button ID="Button4" runat="server" OnClick="Button4_Click" Text="Hide All Orders" class="btn btn-dark" Height="38px" Width="160px" />
            <br />
            <br />
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" DataKeyNames="orderid" DataSourceID="SqlDataSource2" Visible="False">
                <Columns>
                    <asp:BoundField DataField="orderid" HeaderText="Order Id" ReadOnly="True" SortExpression="orderid" />
                    <asp:BoundField DataField="sno" HeaderText="S.No." SortExpression="sno" />
                    <asp:BoundField DataField="productid" HeaderText="Product Id" SortExpression="productid" />
                    <asp:BoundField DataField="productname" HeaderText="Product Name" SortExpression="productname" />
                    <asp:BoundField DataField="price" HeaderText="Price" SortExpression="price" />
                    <asp:BoundField DataField="quantity" HeaderText="Quantity" SortExpression="quantity" />
                    <asp:BoundField DataField="dateoforder" HeaderText="Date Of Order" SortExpression="dateoforder" />
                    <asp:BoundField DataField="totprice" HeaderText="Total Price" SortExpression="totprice" />
                    <asp:BoundField DataField="disprice" HeaderText="Discount Price" SortExpression="disprice" />
                    <asp:BoundField DataField="time" HeaderText="Time" SortExpression="time" />
                </Columns>
            </asp:GridView>
            <br />
            <asp:GridView ID="GridView2" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" DataKeyNames="orderid" DataSourceID="SqlDataSource3" Visible="False">
                <Columns>
                    <asp:BoundField DataField="orderid" HeaderText="Order Id" ReadOnly="True" SortExpression="orderid" />
                    <asp:BoundField DataField="sno" HeaderText="S.No." SortExpression="sno" />
                    <asp:BoundField DataField="productid" HeaderText="Product Id" SortExpression="productid" />
                    <asp:BoundField DataField="productname" HeaderText="Product Name" SortExpression="productname" />
                    <asp:BoundField DataField="price" HeaderText="Price" SortExpression="price" />
                    <asp:BoundField DataField="quantity" HeaderText="Quantity" SortExpression="quantity" />
                    <asp:BoundField DataField="dateoforder" HeaderText="Date Of Order" SortExpression="dateoforder" />
                    <asp:BoundField DataField="totprice" HeaderText="Total Price" SortExpression="totprice" />
                    <asp:BoundField DataField="disprice" HeaderText="Discount Price" SortExpression="disprice" />
                    <asp:BoundField DataField="time" HeaderText="Time" SortExpression="time" />
                </Columns>
            </asp:GridView>
            <br />
            <br />
            <asp:Label ID="Label1" runat="server" Text="Label" Visible="False"></asp:Label>
            <br />
            <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:StudentlogConnectionString %>" SelectCommand="SELECT * FROM [orderdetails] ORDER BY [dateoforder] DESC, [time], [quantity]" DeleteCommand="DELETE FROM [orderdetails] WHERE [orderid] = @orderid" InsertCommand="INSERT INTO [orderdetails] ([orderid], [sno], [productid], [productname], [price], [quantity], [dateoforder], [totprice], [disprice], [time]) VALUES (@orderid, @sno, @productid, @productname, @price, @quantity, @dateoforder, @totprice, @disprice, @time)" UpdateCommand="UPDATE [orderdetails] SET [sno] = @sno, [productid] = @productid, [productname] = @productname, [price] = @price, [quantity] = @quantity, [dateoforder] = @dateoforder, [totprice] = @totprice, [disprice] = @disprice, [time] = @time WHERE [orderid] = @orderid">
                <DeleteParameters>
                    <asp:Parameter Name="orderid" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="orderid" Type="String" />
                    <asp:Parameter Name="sno" Type="Int32" />
                    <asp:Parameter Name="productid" Type="Int32" />
                    <asp:Parameter Name="productname" Type="String" />
                    <asp:Parameter Name="price" Type="Int32" />
                    <asp:Parameter Name="quantity" Type="Int32" />
                    <asp:Parameter Name="dateoforder" Type="String" />
                    <asp:Parameter Name="totprice" Type="String" />
                    <asp:Parameter Name="disprice" Type="String" />
                    <asp:Parameter Name="time" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="sno" Type="Int32" />
                    <asp:Parameter Name="productid" Type="Int32" />
                    <asp:Parameter Name="productname" Type="String" />
                    <asp:Parameter Name="price" Type="Int32" />
                    <asp:Parameter Name="quantity" Type="Int32" />
                    <asp:Parameter Name="dateoforder" Type="String" />
                    <asp:Parameter Name="totprice" Type="String" />
                    <asp:Parameter Name="disprice" Type="String" />
                    <asp:Parameter Name="time" Type="String" />
                    <asp:Parameter Name="orderid" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <br />
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:StudentlogConnectionString %>" SelectCommand="SELECT DISTINCT [orderid] FROM [orderdetails]"></asp:SqlDataSource>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:StudentlogConnectionString %>" SelectCommand="SELECT * FROM [orderdetails] WHERE ([orderid] = @orderid)">
                <SelectParameters>
                    <asp:ControlParameter ControlID="DropDownList1" Name="orderid" PropertyName="SelectedValue" Type="String" />
                </SelectParameters>
            </asp:SqlDataSource>
            <br />
        </div>
    </form>
</body>
</html>
